# Generated by Django 5.1 on 2024-09-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
